DB_HOST = 'localhost'
DB_PORT = 5432
DB_NAME = 'mdl'
DB_USER = 'dmk'
DB_PASSWORD = 'dmk5402'

SQLALCHEMY_URL = f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
ASYNC_SQLALCHEMY_URL = f'postgresql+asyncpg://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
SQLALCHEMY_ECHO = False
SQLALCHEMY_POOL_SIZE = 5
SQLALCHEMY_MAX_OVERFLOW = 2

# Datetime configs
USE_TIMEZONE = True
DATETIME_FORMAT = '%d-%m-%y %H:%M:%S'
DATE_FORMAT = '%d-%m-%y'
