"""assets added

Revision ID: 1d41c49aec29
Revises: f4af54839b5a
Create Date: 2022-07-18 15:40:25.405093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d41c49aec29'
down_revision = 'f4af54839b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('assets')
    # ### end Alembic commands ###
