"""assets type added

Revision ID: bc1a065a2a7b
Revises: 1d41c49aec29
Create Date: 2022-07-18 17:36:58.063984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1a065a2a7b'
down_revision = '1d41c49aec29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('type', sa.SmallInteger(), nullable=False))
    op.create_unique_constraint('unique_tg_id_and_type', 'assets', ['tg_id', 'type'])
    op.create_unique_constraint(None, 'assets', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_constraint('unique_tg_id_and_type', 'assets', type_='unique')
    op.drop_column('assets', 'type')
    # ### end Alembic commands ###
