"""customer phone number added

Revision ID: fd483f2f91b1
Revises: 03df5d3c05fe
Create Date: 2022-07-07 13:36:20.433918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd483f2f91b1'
down_revision = '03df5d3c05fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
